server:
  port: 9000
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: TmplProject
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tmpl?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: wgbsql
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.project.name.repository.*.entity