server:
  port: 9000
spring:
  application:
    name: TmplProject
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tmpl?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    data-username: localhost
    data-password: wgbsql

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.project.name.repository.*.entity